# see orb options at
# https://github.com/cypress-io/circleci-orb
version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  notify_coveralls:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: /
      - run: ls -la /
      - run: ls -la /tmp
      - run: ls -la /tmp/coverage
      - run: mkdir .nyc_output || true
      - run: npx nyc merge /tmp/coverage
      - run: mv coverage.json .nyc_output/out.json
      - run: npx nyc report --reporter lcov --report-dir coverage
      - run:
          # https://docs.coveralls.io/parallel-build-webhook
          name: Tell Coveralls all jobs are done
          command: |
            curl https://coveralls.io/webhook/?repo_token=$COVERALLS_REPO_TOKEN \
              -d "payload[build_num]=$CIRCLE_WORKFLOW_ID&payload[status]=done"

workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress/base-10
          pre-steps:
            - run: npm config set unsafe-perm true
      - cypress/run:
          requires:
            - cypress/install
          executor: cypress/base-10
          parallel: true
          parallelism: 4
          no-workspace: true
          start: npm run start:coverage
          wait-on: http://localhost:4100
          record: true
          post-steps:
            - store_artifacts:
                path: coverage
            # if this machine had no tests to run
            # there will be no coverage report
            - run: npx nyc report --reporter=text || true

            # collect all code coverage reports
            - run: mkdir /tmp/coverage || true
            - run: touch /tmp/coverage/.placeholder || true
            - run: cp coverage/coverage-final.json /tmp/coverage/coverage-$CIRCLE_NODE_INDEX.json || true
            - run: ls -la /tmp/coverage
            - persist_to_workspace:
                root: /tmp
                paths:
                  - coverage/*

            # send code coverage to coveralls.io
            # https://coveralls.io/github/cypress-io/cypress-example-realworld
            # but because we run tests in parallel, tell Coveralls
            # to merge the reports into a single complete one
            # https://docs.coveralls.io/parallel-build-webhook
            - run:
                environment:
                  COVERALLS_PARALLEL: 1
                command: CIRCLE_BUILD_NUM=$CIRCLE_WORKFLOW_ID npm run coveralls || true
      - notify_coveralls:
          requires:
            - cypress/run
