# see orb options at
# https://github.com/cypress-io/circleci-orb
version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  notify_coveralls:
    executor: cypress/base-10
    steps:
      - run:
          # https://docs.coveralls.io/parallel-build-webhook
          name: Tell Coveralls all jobs are done
          command: curl https://coveralls.io/webhook/?repo_token=$COVERALLS_REPO_TOKEN

workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress/base-10
          pre-steps:
            - run: npm config set unsafe-perm true
      - cypress/run:
          requires:
            - cypress/install
          executor: cypress/base-10
          parallel: true
          parallelism: 4
          no-workspace: true
          start: npm run start:coverage
          wait-on: http://localhost:4100
          record: true
          post-steps:
            - store_artifacts:
                path: coverage
            # if this machine had no tests to run
            # there will be no coverage report
            - run: npx nyc report --reporter=text || true
            # send code coverage to coveralls.io
            # https://coveralls.io/github/cypress-io/cypress-example-realworld
            # but because we run tests in parallel, tell Coveralls
            # to merge the reports into a single complete one
            # https://docs.coveralls.io/parallel-build-webhook
            - run: COVERALLS_PARALLEL=1 npm run coveralls || true
      - notify_coveralls:
          requires:
            - cypress/run
